service: restapi-dynamodb

provider: 
  name: aws
  runtime: nodejs14.x
  stage: api
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE_NAME: ${{self:custom.postsTableName}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action: [
        "dynamodb:DescribeTable",
        "dynamodb:Query",
        "dynamodb:Scan",
        "dynamodb:GetItem",
        "dynamodb:PutItem",
        "dynamodb:UpdateItem",
        "dynamodb:DeleteItem",
      ]
      Resource: "arn:aws:dynamodb:${{self:provider.region}}:*:table/${{self:custom.postsTableName}}"


custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: src/index.getPost
    name: getPost
    memorySire: 128 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: GET

  createPost:
    handler: src/index.createPost
    name: createPost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/create
          method: POST

  updatePost:
    handler: src/index.updatePost
    name: updatePost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: PUT

  deletePost:
    handler: src/index.deletePost
    name: deletePost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: DELETE

  getAllPost:
    handler: src/index.getAllPost
    name: getAllPost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: posts
          method: DELETE

resources:
  Resources: 
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema: 
          - AttributeName: postId
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
