service: restapi-dynamodb

provider: 
  name: aws
  runtime: nodejs14.x
  stage: api
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE_NAME: ${{self:custom.postsTableName}}

custom:
  postsTableName: posts-table-${{self:provider.stage}}

plugins:
  - serverless-iam-roles-per-function

functions:
  getPost:
    handler: src/index.getPost
    name: getPost
    memorySire: 128 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Actions: 
          - "dynamodb: GetItem"
        Resource: "arn:aws:dynamodb:${{self:provider.region}}:913831160226:table/restApi-auto-deloy"
  
  createPost:
    handler: src/index.createPost
    name: createPost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/create
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Actions: 
          - "dynamodb: PutItem"
        Resource: "arn:aws:dynamodb:${{self:provider.region}}:913831160226:table/restApi-auto-deloy"

  updatePost:
    handler: src/index.updatePost
    name: updatePost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Actions: 
          - "dynamodb: UpdateItem"
        Resource: "arn:aws:dynamodb:${{self:provider.region}}:913831160226:table/restApi-auto-deloy"
        
  deletePost:
    handler: src/index.deletePost
    name: deletePost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: post/{postId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Actions: 
          - "dynamodb: DeleteItem"
        Resource: "arn:aws:dynamodb:${{self:provider.region}}:913831160226:table/restApi-auto-deloy"

  getAllPost:
    handler: src/index.getAllPost
    name: getAllPost
    memorySire: 123 #mb
    timeout: 5 #seconds
    events: 
      - http:
          path: posts
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Actions: 
          - "dynamodb: Scan"
        Resource: "arn:aws:dynamodb:${{self:provider.region}}:913831160226:table/restApi-auto-deloy"

resources:
  Resources: 
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AtrributeType: S
        KeySchema: 
          - AttributeName: postId
            KeyType: HASH
        ProvisonedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
